apiVersion: v1
kind: Namespace
metadata:
  name: app-lab
---
# BACKEND (Django)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: app-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: 580248541584.dkr.ecr.us-east-1.amazonaws.com/users-api:v6
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"

---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: app-lab
spec:
  type: ClusterIP
  selector:
    app: users-api
  ports:
    - port: 8000
      targetPort: 8000
---
# NOTIFIER (Flask)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: app-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: 580248541584.dkr.ecr.us-east-1.amazonaws.com/users-api:ultimo
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
  namespace: app-lab
spec:
  type: ClusterIP
  selector:
    app: notifier
  ports:
    - port: 5000
      targetPort: 5000
---
# FRONTEND (Nginx + HTML)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 580248541584.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: app-lab
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
